package org.example;

import junit.framework.Test;
import junit.framework.TestCase;
import junit.framework.TestSuite;

/**
 * Basic JUnit test scaffold generated by the project template.
 *
 * This test demonstrates the standard JUnit 3 style test suite. It contains
 * a trivial passing test; expand it to cover application behavior as needed.
 */
public class AppTest
    extends TestCase
{
    public AppTest( String testName )
    {
        super( testName );
    }

    public static Test suite()
    {
        return new TestSuite( AppTest.class );
    }

    public void testApp()
    {
        assertTrue( true );
    }
}
